name: misterblast_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  riverpod: ^2.6.1
  intl: ^0.20.2
  easy_localization: ^3.0.7+1
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  firebase_crashlytics: ^4.3.3
  firebase_analytics: ^11.4.3
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  firebase_remote_config: ^5.4.1
  riverpod_generator: ^2.6.4
  flutter_dotenv: ^5.2.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  change_app_package_name: ^1.5.0
  cached_network_image: ^3.4.1
  fl_chart: ^0.71.0
  auto_size_text: ^3.0.0
  google_nav_bar: ^5.0.7
  gpt_markdown: ^1.0.19
  flutter_math_fork: ^0.7.3
  animations: ^2.0.11
  toastification: ^3.0.2
  logger: ^2.5.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^5.0.0
  file_picker: ^10.1.9
  url_launcher: ^6.3.1
  rename_app: ^1.6.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  flutter_launcher_icons: "^0.14.4"


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/app-logo.png"

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/locales/
    - assets/images/
    - shorebird.yaml
